export const CATEGORIES = [
    { value: "bakery", label: "Bakery" },
    { value: "bath and body", label: "Bath and Body" },
    { value: "beverages", label: "Beverages" },
    { value: "canned goods", label: "Canned Goods" },
    { value: "dairy", label: "Dairy" },
    { value: "deli", label: "Deli" },
    { value: "dry goods", label: "Dry Goods" },
    { value: "frozen foods", label: "Frozen Foods" },
    { value: "household", label: "Household" },
    { value: "meat", label: "Meat" },
    { value: "pharmacy", label: "Pharmacy" },
    { value: "produce", label: "Produce" },
    { value: "snacks", label: "Snacks" },
    { value: "other", label: "Other" },
];